import type React from "react";

export const s = {
  wrap: { padding: 24 } as React.CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } as React.CSSProperties,
  title: { fontWeight: 700, fontSize: 15 } as React.CSSProperties,
  counter: {
    fontSize: 12,
    padding: "2px 8px",
    borderRadius: 12,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    fontWeight: 600,
  } as React.CSSProperties,
  search: {
    width: "100%",
    maxWidth: 220,
    marginLeft: "auto",
    padding: "5px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } as React.CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 16 } as React.CSSProperties,
  row: (enabled: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 6,
    background: enabled ? "var(--bg-surface)" : "transparent",
    border: "1px solid var(--border)",
    marginBottom: 4,
    opacity: enabled ? 1 : 0.55,
  }),
  drag: { cursor: "grab", color: "var(--text-muted)", flexShrink: 0, fontSize: 16 } as React.CSSProperties,
  checkbox: { width: 15, height: 15, flexShrink: 0, cursor: "pointer" } as React.CSSProperties,
  skillName: { flex: 1, fontSize: 13, fontWeight: 500 } as React.CSSProperties,
  typeBadge: (color: string): React.CSSProperties => ({
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: color + "22",
    color,
    fontWeight: 600,
  }),
  unlinkedRow: (enabled: boolean): React.CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 6,
    background: "transparent",
    border: "1px solid var(--border)",
    marginBottom: 4,
    opacity: 0.4,
  }),
};
