import type React from "react";

export const s = {
  body: { padding: 24 } as React.CSSProperties,
  field: { marginBottom: 16 } as React.CSSProperties,
  fieldRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
    marginBottom: 16,
  } as React.CSSProperties,
  fieldLast: { marginBottom: 0 } as React.CSSProperties,
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 6,
  } as React.CSSProperties,
  labelRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  } as React.CSSProperties,
  tokenCount: {
    fontSize: 11,
    color: "var(--text-muted)",
    fontWeight: 500,
  } as React.CSSProperties,
  input: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } as React.CSSProperties,
  textarea: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    boxSizing: "border-box" as const,
    resize: "vertical" as const,
    minHeight: 260,
    lineHeight: 1.5,
  } as React.CSSProperties,
  infoBox: {
    display: "flex",
    gap: 10,
    padding: "10px 14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    marginBottom: 20,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } as React.CSSProperties,
  infoIcon: {
    flexShrink: 0,
    marginTop: 1,
    color: "var(--text-muted)",
  } as React.CSSProperties,
  toggleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 6,
  } as React.CSSProperties,
  toggleTrack: (enabled: boolean): React.CSSProperties => ({
    width: 36,
    height: 20,
    borderRadius: 10,
    background: enabled ? "var(--accent)" : "var(--bg-hover)",
    border: "none",
    cursor: "pointer",
    position: "relative",
    transition: "background .15s",
    flexShrink: 0,
    padding: 0,
  }),
  toggleThumb: (enabled: boolean): React.CSSProperties => ({
    position: "absolute",
    top: 2,
    left: enabled ? 18 : 2,
    width: 16,
    height: 16,
    borderRadius: "50%",
    background: "white",
    boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
    transition: "left .15s",
  }),
  footer: {
    display: "flex",
    gap: 8,
    justifyContent: "flex-end",
    alignItems: "center",
  } as React.CSSProperties,
  successMsg: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-secondary)",
    fontStyle: "italic",
  } as React.CSSProperties,
};
