import type React from "react";

export const s = {
  section: { marginBottom: 24 } as React.CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 6,
    display: "block",
  } as React.CSSProperties,
  helper: { fontSize: 11, color: "var(--text-muted)", marginTop: 4 } as React.CSSProperties,
  input: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } as React.CSSProperties,
  typePicker: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  } as React.CSSProperties,
  typeBtn: (active: boolean, color: string): React.CSSProperties => ({
    padding: "9px 14px",
    borderRadius: 8,
    border: `1.5px solid ${active ? color : "var(--border)"}`,
    background: active ? color + "22" : "var(--bg-input)",
    color: active ? color : "var(--text-secondary)",
    fontSize: 13,
    fontWeight: active ? 600 : 400,
    cursor: "pointer",
    textAlign: "left",
    transition: "border-color .12s, background .12s, color .12s",
  }),
  editorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  } as React.CSSProperties,
  filename: { fontSize: 12, color: "var(--text-muted)", fontFamily: "monospace" } as React.CSSProperties,
  unsaved: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
  } as React.CSSProperties,
  tokens: { fontSize: 11, color: "var(--text-muted)", marginLeft: "auto" } as React.CSSProperties,
  saveRow: { display: "flex", justifyContent: "flex-end", marginTop: 16 } as React.CSSProperties,
};
