import type React from "react";

export const s = {
  body: { padding: 24 } as React.CSSProperties,
  previewBody2: { padding: 24 } as React.CSSProperties,
  modeTabs: { display: "flex", gap: 8, marginBottom: 16 } as React.CSSProperties,
  modeBtn: (active: boolean): React.CSSProperties => ({
    padding: "7px 18px",
    borderRadius: 6,
    border: `1.5px solid ${active ? "var(--accent)" : "var(--border)"}`,
    background: active ? "var(--accent)" : "var(--bg-input)",
    color: active ? "#fff" : "var(--text-secondary)",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: active ? 600 : 400,
  }),
  dropZone: (drag: boolean): React.CSSProperties => ({
    width: "100%",
    padding: "28px 20px",
    borderRadius: 8,
    border: `2px dashed ${drag ? "var(--accent)" : "var(--border)"}`,
    background: drag ? "var(--accent-subtle, #6366f111)" : "var(--bg-input)",
    color: "var(--text-secondary)",
    fontSize: 13,
    textAlign: "center",
    cursor: "pointer",
    boxSizing: "border-box" as const,
    transition: "border-color .15s, background .15s",
  }),
  dropZoneHint: { fontSize: 11, color: "var(--text-muted)", marginTop: 4 } as React.CSSProperties,
  fileName: { fontSize: 13, color: "var(--text-primary)", fontWeight: 500 } as React.CSSProperties,
  urlInput: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } as React.CSSProperties,
  error: { color: "#ef4444", fontSize: 13, marginTop: 10 } as React.CSSProperties,
  trustWarning: {
    background: "#f59e0b22",
    border: "1px solid #f59e0b44",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    color: "#f59e0b",
    marginBottom: 16,
  } as React.CSSProperties,
  previewCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 8,
  } as React.CSSProperties,
  previewHeader: {
    padding: "10px 16px",
    background: "var(--bg-surface)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } as React.CSSProperties,
  previewName: { fontWeight: 600, fontSize: 13 } as React.CSSProperties,
  previewType: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } as React.CSSProperties,
  previewBody: {
    padding: 16,
    fontSize: 12,
    maxHeight: 180,
    overflow: "auto",
    color: "var(--text-muted)",
    whiteSpace: "pre-wrap" as const,
  } as React.CSSProperties,
  footer: { display: "flex", gap: 8, justifyContent: "flex-end" } as React.CSSProperties,
};
