import type React from "react";

export const s = {
  modeTabs: { display: "flex", gap: 8, marginBottom: 16 } as React.CSSProperties,
  modeBtn: (active: boolean): React.CSSProperties => ({
    padding: "6px 16px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: active ? "var(--accent)" : "var(--bg-input)",
    color: active ? "#fff" : "var(--text-primary)",
    cursor: "pointer",
    fontSize: 13,
  }),
  input: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } as React.CSSProperties,
  error: { color: "#ef4444", fontSize: 13, marginTop: 8 } as React.CSSProperties,
  trustWarning: {
    background: "#f59e0b22",
    border: "1px solid #f59e0b44",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    color: "#f59e0b",
    marginBottom: 16,
  } as React.CSSProperties,
  previewCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 8,
  } as React.CSSProperties,
  previewHeader: {
    padding: "10px 16px",
    background: "var(--bg-surface)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } as React.CSSProperties,
  previewName: { fontWeight: 600, fontSize: 13 } as React.CSSProperties,
  previewType: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } as React.CSSProperties,
  previewBody: {
    padding: 16,
    fontSize: 12,
    maxHeight: 180,
    overflow: "auto",
    color: "var(--text-muted)",
    whiteSpace: "pre-wrap" as const,
  } as React.CSSProperties,
  footer: { display: "flex", gap: 8, justifyContent: "flex-end" } as React.CSSProperties,
};
