import type { CSSProperties } from "react";

export const s = {
  wrap: {
    position: "relative",
    display: "inline-block",
  } satisfies CSSProperties,
  panel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    width: 280,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 9,
    boxShadow: "var(--shadow-modal)",
    padding: 12,
    zIndex: 40,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    animation: "ddpop .12s ease",
  } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  headerLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  clearLink: {
    background: "transparent",
    border: "none",
    padding: 0,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent)",
    cursor: "pointer",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    maxHeight: 260,
    overflowY: "auto",
  } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "4px 2px",
  } satisfies CSSProperties,
  agentLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "var(--text-primary)",
    fontWeight: 500,
  } satisfies CSSProperties,
  hint: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  emptyRow: {
    fontSize: 13,
    color: "var(--text-muted)",
    padding: "6px 2px",
  } satisfies CSSProperties,
  configureRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "transparent",
    border: "none",
    padding: "6px 2px 0",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
};
