import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: 24 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  title: { fontWeight: 700, fontSize: 15 } satisfies CSSProperties,
  countBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 10px",
    borderRadius: 999,
    border: "1px solid var(--accent)",
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    flexShrink: 0,
  } satisfies CSSProperties,
  search: {
    width: "100%",
    maxWidth: 220,
    marginLeft: "auto",
    padding: "5px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
    padding: "24px 0",
    textAlign: "center" as const,
  } satisfies CSSProperties,
  row: (dragOver = false): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 6,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    marginBottom: 4,
    outline: dragOver ? "2px solid var(--accent)" : undefined,
    cursor: "default",
  }),
  unlinkedRow: (): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 6,
    background: "transparent",
    border: "1px solid var(--border)",
    marginBottom: 4,
    opacity: 0.55,
  }),
  drag: { cursor: "grab", color: "var(--text-muted)", flexShrink: 0, fontSize: 16 } satisfies CSSProperties,
  dragPlaceholder: { flexShrink: 0, fontSize: 16, opacity: 0, pointerEvents: "none" as const } satisfies CSSProperties,
  checkbox: { width: 15, height: 15, flexShrink: 0, cursor: "pointer" } satisfies CSSProperties,
  docName: { fontWeight: 500, fontSize: 13, flexShrink: 0 } satisfies CSSProperties,
  docPath: {
    flex: 1,
    fontSize: 12,
    color: "var(--text-muted)",
    overflow: "hidden",
    whiteSpace: "nowrap" as const,
    textOverflow: "ellipsis",
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  rootBadge: (folder: string): CSSProperties => {
    const palette: Record<string, { color: string; background: string }> = {
      specs: { color: "var(--accent-text)", background: "var(--accent-bg)" },
      docs: { color: "var(--ok)", background: "var(--ok-bg)" },
      insights: { color: "var(--warn)", background: "var(--warn-bg)" },
    };
    const c = palette[folder];
    return {
      fontSize: 11,
      padding: "2px 6px",
      borderRadius: 4,
      background: c?.background ?? "var(--bg-hover)",
      color: c?.color ?? "var(--text-secondary)",
      fontWeight: 600,
      flexShrink: 0,
    };
  },
  previewBtn: { flexShrink: 0 } satisfies CSSProperties,
  staleBadge: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontWeight: 600,
    flexShrink: 0,
  } satisfies CSSProperties,
  divider: {
    borderTop: "1px solid var(--border)",
    margin: "8px 0",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 16,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footerNotice: { color: "var(--text-muted)" } satisfies CSSProperties,
  warning: {
    color: "var(--warn)",
    fontWeight: 600,
  } satisfies CSSProperties,
  previewBody: { padding: 20 } satisfies CSSProperties,
  previewState: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
