import type { CSSProperties } from "react";

/** Shared styles across the wizard shell + all 4 steps (design/02–05). */
export const s = {
  stepsBar: { padding: "18px 24px 0" } satisfies CSSProperties,
  body: { padding: "20px 24px", minHeight: 320, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%" } satisfies CSSProperties,
  footerRight: { display: "flex", gap: 10, marginLeft: "auto" } satisfies CSSProperties,

  // ---- Target step ----
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 14,
  } satisfies CSSProperties,
  card: (selected: boolean, disabled: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 16,
    borderRadius: 9,
    border: `1px solid ${selected ? "var(--accent)" : "var(--border-strong)"}`,
    background: "var(--bg-elevated)",
    opacity: disabled ? 0.5 : 1,
    cursor: disabled ? "not-allowed" : "pointer",
    textAlign: "left",
  }),
  cardHeader: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  cardTitle: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  cardDesc: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,

  // ---- Preview step ----
  // maxHeight caps the two-panel region so the file's contents scroll INSIDE
  // `contentBody` (below) instead of growing the whole modal — the Modal shell
  // wraps every step in a single `overflow: auto` region, so without a cap here
  // a long YAML scrolls the entire wizard (steps bar + footer) rather than just
  // the preview.
  previewLayout: {
    display: "flex",
    gap: 18,
    flex: 1,
    minHeight: 260,
    maxHeight: "50vh",
  } satisfies CSSProperties,
  filesPanel: { width: 260, flexShrink: 0, display: "flex", flexDirection: "column", gap: 4, overflow: "auto", minHeight: 0 } satisfies CSSProperties,
  filesHeading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  fileRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    fontSize: 12.5,
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
    background: active ? "var(--accent-bg)" : "transparent",
    cursor: "pointer",
    textAlign: "left",
    lineHeight: 1.4,
    wordBreak: "break-all",
  }),
  contentPanel: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
  } satisfies CSSProperties,
  contentHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  contentPath: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  previewNotice: {
    flexShrink: 0,
    padding: "8px 14px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-muted)",
    fontSize: 12,
    lineHeight: 1.4,
  } satisfies CSSProperties,
  contentBody: {
    flex: 1,
    overflow: "auto",
    padding: 14,
    fontSize: 12.5,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    margin: 0,
  } satisfies CSSProperties,
  generating: { flex: 1, display: "grid", placeItems: "center", color: "var(--text-muted)", fontSize: 13 } satisfies CSSProperties,

  // ---- Configure step ----
  section: { marginBottom: 22 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 10,
  } satisfies CSSProperties,
  chipRow: { display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  secretRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 0",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  secretName: { fontSize: 13, color: "var(--text-primary)", flexShrink: 0, minWidth: 170 } satisfies CSSProperties,
  secretDesc: { fontSize: 12, color: "var(--text-muted)", flex: 1 } satisfies CSSProperties,
  secretNote: { fontSize: 11.5, color: "var(--text-muted)", marginTop: 8 } satisfies CSSProperties,
  radioRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 0",
    cursor: "pointer",
  } satisfies CSSProperties,
  radioDot: (active: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    borderRadius: 99,
    border: `1px solid ${active ? "var(--accent)" : "var(--border-strong)"}`,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  }),
  radioDotInner: (active: boolean): CSSProperties => ({
    width: 8,
    height: 8,
    borderRadius: 99,
    background: active ? "var(--accent)" : "transparent",
  }),
  radioLabel: { fontSize: 13.5, color: "var(--text-primary)" } satisfies CSSProperties,
  callout: {
    display: "flex",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  regenerateWarning: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 12.5,
    marginBottom: 16,
  } satisfies CSSProperties,

  // ---- Install step ----
  installCard: (selected: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 16,
    borderRadius: 9,
    border: `1px solid ${selected ? "var(--accent)" : "var(--border-strong)"}`,
    background: "var(--bg-elevated)",
    cursor: "pointer",
    marginBottom: 14,
  }),
  installCardHeader: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  installCardTitle: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)", flex: 1 } satisfies CSSProperties,
  installCardDesc: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  installCardTrailing: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  docsLink: { fontSize: 12.5, color: "var(--accent-text)", textDecoration: "none" } satisfies CSSProperties,
  successBox: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 16,
    borderRadius: 9,
    border: "1px solid var(--ok)",
    background: "var(--ok-bg)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
} as const;
