import type { CSSProperties } from "react";

export const s = {
  column: (accent: string): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    borderRadius: 10,
    border: "1px solid var(--border)",
    borderTopWidth: 2,
    borderTopColor: accent,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  }),
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    padding: "14px 14px 12px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  headerLeft: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    minWidth: 0,
  } satisfies CSSProperties,
  iconBox: (color: string, bg: string): CSSProperties => ({
    width: 30,
    height: 30,
    borderRadius: 7,
    display: "grid",
    placeItems: "center",
    color,
    background: bg,
    flexShrink: 0,
  }),
  name: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  metaLine: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "var(--text-muted)",
    marginTop: 3,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  scorePlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 99,
    border: "1px solid var(--border)",
    display: "grid",
    placeItems: "center",
    color: "var(--text-muted)",
    fontSize: 13,
    flexShrink: 0,
  } satisfies CSSProperties,
  body: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    minHeight: 60,
    flex: 1,
  } satisfies CSSProperties,
  noFindings: {
    fontSize: 12,
    color: "var(--text-muted)",
    padding: "8px 2px",
  } satisfies CSSProperties,
  // Each finding is an inset mini-card with a severity-colored left edge
  // (design/04.png) — the accent identifies the finding type at a glance.
  findingCard: (accent: string): CSSProperties => ({
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    padding: "8px 10px",
    borderRadius: 7,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderLeftWidth: 3,
    borderLeftColor: accent,
  }),
  findingText: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  } satisfies CSSProperties,
  findingTitle: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  findingLoc: {
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  viewTrace: {
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 12,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  findingsCount: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
