import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: 24 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  title: { fontWeight: 700, fontSize: 15 } satisfies CSSProperties,
  counter: {
    fontSize: 12,
    padding: "2px 8px",
    borderRadius: 12,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    fontWeight: 600,
  } satisfies CSSProperties,
  search: {
    width: "100%",
    maxWidth: 220,
    marginLeft: "auto",
    padding: "5px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  row: (enabled: boolean, dragOver = false): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 6,
    background: enabled ? "var(--bg-surface)" : "transparent",
    border: "1px solid var(--border)",
    marginBottom: 4,
    opacity: enabled ? 1 : 0.55,
    outline: dragOver ? "2px solid var(--accent)" : undefined,
    cursor: "default",
  }),
  unlinkedRow: (): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 6,
    background: "transparent",
    border: "1px solid var(--border)",
    marginBottom: 4,
    opacity: 0.4,
  }),
  drag: { cursor: "grab", color: "var(--text-muted)", flexShrink: 0, fontSize: 16 } satisfies CSSProperties,
  dragPlaceholder: { flexShrink: 0, fontSize: 16, opacity: 0, pointerEvents: "none" as const } satisfies CSSProperties,
  checkbox: { width: 15, height: 15, flexShrink: 0, cursor: "pointer" } satisfies CSSProperties,
  skillName: { fontWeight: 500, fontSize: 13, flexShrink: 0 } satisfies CSSProperties,
  skillDesc: {
    flex: 1,
    fontSize: 12,
    color: "var(--text-muted)",
    overflow: "hidden",
    whiteSpace: "nowrap" as const,
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  typeBadge: (color: string): CSSProperties => ({
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: color + "22",
    color,
    fontWeight: 600,
    flexShrink: 0,
  }),
  divider: {
    borderTop: "1px solid var(--border)",
    margin: "8px 0",
  } satisfies CSSProperties,
} as const;
