import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  title: { fontWeight: 700, fontSize: 15 } satisfies CSSProperties,
  search: {
    width: "100%",
    maxWidth: 220,
    marginLeft: "auto",
    padding: "5px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box" as const,
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "16px 0" } satisfies CSSProperties,
  section: { marginBottom: 16 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    letterSpacing: 0.4,
    marginBottom: 6,
    display: "block",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    marginBottom: 4,
  } satisfies CSSProperties,
  checkbox: { width: 15, height: 15, flexShrink: 0, cursor: "pointer" } satisfies CSSProperties,
  docPath: {
    fontWeight: 500,
    fontSize: 13,
    flexShrink: 0,
    fontFamily: "monospace",
  } satisfies CSSProperties,
  docPathFlex: {
    flex: 1,
    fontSize: 13,
    fontFamily: "monospace",
    overflow: "hidden",
    whiteSpace: "nowrap" as const,
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  badge: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    fontWeight: 600,
    flexShrink: 0,
  } satisfies CSSProperties,
  untrackedBadge: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontWeight: 600,
    flexShrink: 0,
  } satisfies CSSProperties,
  staleBadge: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontWeight: 600,
    flexShrink: 0,
  } satisfies CSSProperties,
  tokenCount: {
    fontSize: 11,
    color: "var(--text-muted)",
    marginLeft: "auto",
    flexShrink: 0,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 0",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  warning: {
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 4,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontWeight: 600,
  } satisfies CSSProperties,
  serializesAs: {
    marginTop: 20,
    padding: 12,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  serializesHeader: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.4,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  serializesHint: {
    fontSize: 11,
    color: "var(--text-muted)",
    marginTop: 4,
    marginBottom: 8,
  } satisfies CSSProperties,
  serializesEmpty: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  serializesBlock: {
    fontSize: 12,
    fontFamily: "monospace",
    whiteSpace: "pre-wrap" as const,
    margin: 0,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
} as const;
